package com.xzit.mapper.mybatis;

import com.xzit.model.mybatis.Teacher;
import com.xzit.model.mybatis.TeacherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    long countByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    int deleteByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    int insert(Teacher row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    int insertSelective(Teacher row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    List<Teacher> selectByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    Teacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    int updateByExampleSelective(@Param("row") Teacher row, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    int updateByExample(@Param("row") Teacher row, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    int updateByPrimaryKeySelective(Teacher row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis..teacher
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    int updateByPrimaryKey(Teacher row);
}