package com.xzit.model.mybatis;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Accessors(chain = true)
public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis..teacher.id
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis..teacher.name
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis..teacher.addr
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis..teacher.age
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis..teacher.job
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis..teacher.sal
     *
     * @mbg.generated Tue Jul 29 23:12:59 CST 2025
     */
    private Integer sal;


}